version: '3.8'
services:
  web:
    # command: tail -f /dev/null
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
      - "8001:8001"
    depends_on:
      - "database"
    volumes:
      - .:/backend
      - logvolume01:/var/log
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - .:/database

volumes:
  logvolume01: {}
  dbvolume:

    