# Generated by Django 3.0.8 on 2020-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='username',
            field=models.CharField(default='asdf', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
